spring:
  application:
    name: internaute-microservice # Name for identification in Eureka
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      import: "configserver:"
      import-check:
        enabled: true
  datasource:
    url: jdbc:mysql://internaute-db:3306/internaute_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      prometheus:
        enabled: true
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans # Zipkin Server URL

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

resilience4j:
  retry:
    instances:
      myRetry:
        max-attempts: 3 # Maximum number of retry attempts
        wait-duration: 500ms # Wait time between retries
  rate-limiter:
    instances:
      myRateLimiter:
        limit-for-period: 5 # Maximum 5 requests per period
        limit-refresh-period: 1s # Refresh period for rate limiter
        timeout-duration: 500ms # Timeout duration for rate-limited requests
